name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME || 'your-dockerhub-username/re-shopping-cart-web-app' }}
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER || 'ec2-user' }}
        run: |
          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            # Stop existing container if running
            docker stop re-shopping-cart-web-app || true
            docker rm re-shopping-cart-web-app || true
            
            # Remove old image to free space
            docker rmi ${{ env.DOCKER_IMAGE_NAME }}:latest || true
            
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            
            # Pull latest image
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest
            
            # Run new container
            docker run -d \
              --name re-shopping-cart-web-app \
              --restart unless-stopped \
              -p 8081:8081 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e HIBERNATE_DDL_AUTO=none \
              -e HIBERNATE_SHOW_SQL=false \
              -e THYMELEAF_CACHE=true \
              ${{ env.DOCKER_IMAGE_NAME }}:latest
            
            # Clean up unused images
            docker image prune -f
          EOF

      - name: Verify deployment
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          sleep 10
          curl -f http://${EC2_HOST}:8081/ || echo "Application may still be starting up"